# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    ni_module_dependencies = ['applications']
    module = bld.create_ns3_module('ni', ni_module_dependencies)
    module.source = [
        'model/common/ni-l1-l2-api-common-handler.cc',
        'model/common/ni-udp-transport.cc',
        'model/common/ni-pipe-transport.cc',
        'model/common/ni-pipe.cc',
        'model/common/ni-logging.cc',
        'model/common/ni-utils.cc',
        'model/lte/ni-l1-l2-api-lte-handler.cc',
        'model/lte/ni-l1-l2-api-lte-message.cc',
        'model/lte/ni-l1-l2-api-lte-tables.cc',
        'model/lte/ni-lte-sdr-timing-sync.cc',
        'model/lte/ni-api-rlc-tag-header.cc',
        'model/lte/ni-api-pdcp-tag-header.cc',
        'model/lte/ni-api-radio-bearer-header.cc',
        'model/lte/ni-api-packet-tag-info-header.cc',
        'model/lte/pdcp-lcid.cc',
        'model/lte/pdcp-tagc.cc',
        'model/lte/lwip-tag.cc',
        'model/lte/lwa-tag.cc',
        'model/lte/lwa-header.cc',
        'model/lte/lwip-header.cc',
        'model/lte/lwalwip-header.cc',
        'model/remote-control/ni-remote-control-engine.cc',
        'model/remote-control/ni-local-comms-interface.cc',
        'model/remote-control/ni-parameter-data-base.cc',       
        'model/wifi/ni-wifi-api-msg-handler.cc',
        'model/wifi/ni-wifi-api-msg-helper.cc',
        'model/common/ni-udp-client.cc',
        'model/common/ni-udp-server.cc',
        'model/common/ni-udp-client-server-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('ni')
    module_test.source = [
        'test/ni-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'ni'
    headers.source = [
        'model/ni.h',
        'model/common/ni-common-constants.h',
        'model/common/ni-l1-l2-api.h',
        'model/common/ni-l1-l2-api-common-handler.h',
        'model/common/ni-udp-transport.h',
        'model/common/ni-pipe-transport.h',
        'model/common/ni-pipe.h',
        'model/common/ni-logging.h',
        'model/common/ni-utils.h',
        'model/lte/ni-l1-l2-api-lte.h',
        'model/lte/ni-l1-l2-api-lte-handler.h',
        'model/lte/ni-l1-l2-api-lte-message.h',
        'model/lte/ni-l1-l2-api-lte-tables.h',
        'model/lte/ni-lte-constants.h',
        'model/lte/ni-lte-sdr-timing-sync.h',
        'model/lte/ni-api-rlc-tag-header.h',
        'model/lte/ni-api-pdcp-tag-header.h',
        'model/lte/ni-api-radio-bearer-header.h',
        'model/lte/ni-api-packet-tag-info-header.h',
        'model/lte/pdcp-lcid.h',
        'model/lte/pdcp-tagc.h',
        'model/lte/lwip-tag.h',
        'model/lte/lwa-tag.h',        
        'model/lte/lwa-header.h',
        'model/lte/lwip-header.h',
        'model/lte/lwalwip-header.h',
        'model/remote-control/ni-remote-control-engine.h',
        'model/remote-control/ni-local-comms-interface.h',
        'model/remote-control/ni-parameter-data-base.h',        
        'model/wifi/ni-wifi-api-msg-handler.h',
        'model/wifi/ni-wifi-api-msg-helper.h',
        'model/wifi/ni-wifi-api-msg-types.h',
        'model/wifi/ni-wifi-constants.h',
        'model/common/ni-udp-client.h',
        'model/common/ni-udp-server.h',
        'model/common/ni-udp-client-server-helper.h',        
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

